//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ds.authentication.ui.win.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pua_passportURL
        {
            get
            {
                return ((string)(this["pua_passportURL"]));
            }
            set
            {
                this["pua_passportURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cua_passportURL
        {
            get
            {
                return ((string)(this["cua_passportURL"]));
            }
            set
            {
                this["cua_passportURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pba_passportURL
        {
            get
            {
                return ((string)(this["pba_passportURL"]));
            }
            set
            {
                this["pba_passportURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string caa_passportURL
        {
            get
            {
                return ((string)(this["caa_passportURL"]));
            }
            set
            {
                this["caa_passportURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pua_enoviaURL
        {
            get
            {
                return ((string)(this["pua_enoviaURL"]));
            }
            set
            {
                this["pua_enoviaURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pua_username
        {
            get
            {
                return ((string)(this["pua_username"]));
            }
            set
            {
                this["pua_username"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pua_securitycontext
        {
            get
            {
                return ((string)(this["pua_securitycontext"]));
            }
            set
            {
                this["pua_securitycontext"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pua_password
        {
            get
            {
                return ((string)(this["pua_password"]));
            }
            set
            {
                this["pua_password"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cua_tenant
        {
            get
            {
                return ((string)(this["cua_tenant"]));
            }
            set
            {
                this["cua_tenant"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sel_platform_type
        {
            get
            {
                return ((int)(this["sel_platform_type"]));
            }
            set
            {
                this["sel_platform_type"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sel_auth_method
        {
            get
            {
                return ((int)(this["sel_auth_method"]));
            }
            set
            {
                this["sel_auth_method"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pba_enoviaURL
        {
            get
            {
                return ((string)(this["pba_enoviaURL"]));
            }
            set
            {
                this["pba_enoviaURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pba_servicename
        {
            get
            {
                return ((string)(this["pba_servicename"]));
            }
            set
            {
                this["pba_servicename"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pba_username
        {
            get
            {
                return ((string)(this["pba_username"]));
            }
            set
            {
                this["pba_username"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pba_securitycontext
        {
            get
            {
                return ((string)(this["pba_securitycontext"]));
            }
            set
            {
                this["pba_securitycontext"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string caa_enoviaURL
        {
            get
            {
                return ((string)(this["caa_enoviaURL"]));
            }
            set
            {
                this["caa_enoviaURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string caa_serviceId
        {
            get
            {
                return ((string)(this["caa_serviceId"]));
            }
            set
            {
                this["caa_serviceId"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string caa_tenant
        {
            get
            {
                return ((string)(this["caa_tenant"]));
            }
            set
            {
                this["caa_tenant"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string caa_securityContext
        {
            get
            {
                return ((string)(this["caa_securityContext"]));
            }
            set
            {
                this["caa_securityContext"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cua_enoviaURL
        {
            get
            {
                return ((string)(this["cua_enoviaURL"]));
            }
            set
            {
                this["cua_enoviaURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cua_securitycontext
        {
            get
            {
                return ((string)(this["cua_securitycontext"]));
            }
            set
            {
                this["cua_securitycontext"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cua_username
        {
            get
            {
                return ((string)(this["cua_username"]));
            }
            set
            {
                this["cua_username"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cua_password
        {
            get
            {
                return ((string)(this["cua_password"]));
            }
            set
            {
                this["cua_password"] = value;
            }
        }
    }
}
